name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/01d.png
    - assets/images/01n.png
    - assets/images/02d.png
    - assets/images/02n.png
    - assets/images/03d.png
    - assets/images/03n.png
    - assets/images/04d.png
    - assets/images/04n.png
    - assets/images/09d.png
    - assets/images/09n.png
    - assets/images/10d.png
    - assets/images/10n.png
    - assets/images/11d.png
    - assets/images/11n.png
    - assets/images/13d.png
    - assets/images/13n.png
    - assets/images/50d.png
    - assets/images/50n.png
